Repository hmcts/ccd-admin-web, pull requests merged in 2019-07, with the labels that each got.

#229 RDM-5197 Sanitize BE data that is passed to response. Update README. Igno…
  .gitignore
  README.md
  infrastructure/main.tf
  package.json
  src/main/app.ts
  src/main/routes/confirmDeleteItem.ts
  src/main/routes/createDefinition.ts
  src/main/routes/createUser.ts
  src/main/routes/home.ts
  src/main/routes/importDefinition.ts
  src/main/routes/jurisdiction.ts
  src/main/routes/updateDefinition.ts
  src/main/routes/updateUser.ts
  src/main/routes/userRoles.ts
  src/main/util/error_unauthorized_role.ts
  src/main/util/render.ts
  src/main/views/definition/create-definition-form.html
  yarn.lock
Labels: bug, ns:ccd-admin-web-pr-229

#233 RDM-5330-update ccd to use new docker registry url
  Dockerfile
  acb.tpl.yaml
Labels: ns:ccd-admin-web-pr-233

#234 RDM-5204 - set secure flag for the SSL cookie
  charts/ccd-admin-web/values.aat.template.yaml
  charts/ccd-admin-web/values.template.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  src/main/routes/oauth2redirect.ts
  src/test/routes/oauth2redirect.spec.ts
Labels: ns:ccd-admin-web-pr-234

#235 RDM-5351 - fixed sanitize issue with json object.
  README.md
  config/default.yaml
  src/main/routes/createDefinition.ts
  src/main/routes/createUser.ts
  src/main/routes/importDefinition.ts
  src/main/routes/jurisdiction.ts
  src/main/routes/updateDefinition.ts
  src/main/routes/updateUser.ts
  src/main/routes/userRoles.ts
  src/main/util/render.ts
Labels: ns:ccd-admin-web-pr-235
