Repository hmcts/ccd-admin-web, pull requests merged in 2019-03, with the labels that each got.

#182 RDM-4210: Fix routing on error handler
  src/main/app.ts
Labels: checkpoint, ns:ccd-admin-web-pr-182

#184 Update SAAT with Sidam
  infrastructure/saat.tfvars
Labels: ns:ccd-admin-web-pr-184

#180 RDM 4013 Restrict visibility of Manage User Profiles link in CCD Admin Web to users with the ccd-manage-userprofile role
  .gitignore
  charts/ccd-admin-web/values.aat.template.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  src/main/app.test-admin-web-roles-authorized.ts
  src/main/app.ts
  src/main/role/admin-web-role-authorizer-filter.ts
  src/main/routes/confirmDeleteItem.ts
  src/main/routes/createDefinition.ts
  src/main/routes/createUser.ts
  src/main/routes/home.ts
  src/main/routes/jurisdiction.ts
  src/main/routes/updateDefinition.ts
  src/main/routes/updateUser.ts
  src/main/routes/userProfiles.ts
  src/main/routes/userRoles.ts
  src/main/util/error_unauthorized_role.ts
  src/main/util/render.ts
  src/main/views/error.html
  src/main/views/menu.html
  src/main/views/user-profiles.html
  src/test/role/admin-web-role-authorizer-filter.spec.ts
  src/test/routes/confirmDeleteItem.spec.ts
  src/test/routes/createDefinition.spec.ts
  src/test/routes/createUser.spec.ts
  src/test/routes/home.spec.ts
  src/test/routes/importDefinition.spec.ts
  src/test/routes/jurisdiction.spec.ts
  src/test/routes/userProfiles.spec.ts
  src/test/routes/userRoles.spec.ts
Labels: ns:ccd-admin-web-pr-180

#188 RDM-4252: Improve handling and display of errors on Import Definition page
  package.json
  src/main/app.test.ts
  src/main/app.ts
  src/main/routes/importDefinition.ts
  src/main/views/importDefinition.html
  src/main/views/macros/formElements.html
  src/main/views/response.html
  src/test/routes/confirmDeleteItem.spec.ts
  src/test/routes/importDefinition.spec.ts
  yarn.lock
Labels: checkpoint, ns:ccd-admin-web-pr-188

#194 RDM-4253: Access Control
  src/main/app.test-admin-web-roles-authorized.ts
  src/main/role/admin-web-role-authorizer-filter.ts
  src/main/routes/confirmDeleteItem.ts
  src/main/routes/createDefinition.ts
  src/main/routes/createUser.ts
  src/main/routes/definitions.ts
  src/main/routes/deleteDefinition.ts
  src/main/routes/deleteUser.ts
  src/main/routes/importDefinition.ts
  src/main/routes/updateDefinition.ts
  src/main/routes/updateUser.ts
  src/main/routes/userRoles.ts
  src/main/views/menu.html
  src/test/routes/confirmDeleteItem.spec.ts
  src/test/routes/createDefinition.spec.ts
  src/test/routes/createUser.spec.ts
  src/test/routes/definitions.spec.ts
  src/test/routes/deleteDefinition.spec.ts
  src/test/routes/deleteUser.spec.ts
  src/test/routes/importDefinition.spec.ts
  src/test/routes/updateDefinition.spec.ts
  src/test/routes/updateUser.spec.ts
  src/test/routes/userProfiles.spec.ts
  src/test/routes/userRoles.spec.ts
Labels: checkpoint, ns:ccd-admin-web-pr-194

#196 Switch AAT to SIDAM
  infrastructure/aat.tfvars
Labels: ns:ccd-admin-web-pr-196
