Repository hmcts/ccd-admin-web, pull requests merged in 2019-02, with the labels that each got.

#149 Migrate to Helm charts
  Jenkinsfile_CNP
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/requirements.yaml
  charts/ccd-admin-web/values.aat.template.yaml
  charts/ccd-admin-web/values.template.yaml
  kubernetes/config.aat.yaml
  kubernetes/config.saat.yaml
  kubernetes/deployment.template.yaml
Labels: ns:ccd-admin-web-pr-149

#150 Add stale bot config
  .github/stale.yml
Labels: ns:ccd-admin-web-pr-150

#157 Use https and port 8443 for SIDAM on SAAT
  infrastructure/saat.tfvars
Labels: ns:ccd-admin-web-pr-157

#155 cnp-1131-acr-tasks
  .dockerignore
  .gitignore
  Dockerfile
  acb.tpl.yaml
Labels: ns:ccd-admin-web-pr-155

#166 Upgrade express and serve-favicon to eliminate fresh vulnerability
  yarn.lock
Labels: ns:ccd-admin-web-pr-166

#174 RDM-4020: Implement role whitelist-based access control
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  package.json
  src/main/app.ts
  src/main/role/roles-based-authorizer.ts
  src/main/role/whitelist-roles-authorizer.ts
  src/main/user/auth-checker-user-only-filter.ts
  src/main/user/user-request-authorizer.ts
  src/main/views/error-message.html
  src/main/views/error.html
  src/test/role/roles-based-authorizer.spec.ts
  src/test/role/whitelist-roles-authorizer.spec.ts
  src/test/routes/confirmDeleteItem.spec.ts
  src/test/routes/createDefinition.spec.ts
  src/test/routes/createUser.spec.ts
  src/test/routes/definitions.spec.ts
  src/test/routes/deleteDefinition.spec.ts
  src/test/routes/deleteUser.spec.ts
  src/test/routes/home.spec.ts
  src/test/routes/jurisdiction.spec.ts
  src/test/routes/updateDefinition.spec.ts
  src/test/routes/updateUser.spec.ts
  src/test/routes/userProfiles.spec.ts
  src/test/routes/userRoles.spec.ts
  src/test/user/auth-checker-user-only-filter.spec.ts
  src/test/user/user-request-authorizer.spec.ts
Labels: checkpoint, ns:ccd-admin-web-pr-174

#167 Remove hmcts user as it will be the default user
  Dockerfile
Labels: docker-optimisation, ns:ccd-admin-web-pr-167

#178 RDM-4003: Move Import Definition page from initial screen
  src/main/app.test.ts
  src/main/app.ts
  src/main/import-all/LICENSE
  src/main/import-all/README.md
  src/main/import-all/index.ts
  src/main/router/routerFinder.ts
  src/main/routes/confirmDeleteItem.ts
  src/main/routes/createDefinition.ts
  src/main/routes/createUser.ts
  src/main/routes/definitions.ts
  src/main/routes/deleteDefinition.ts
  src/main/routes/deleteUser.ts
  src/main/routes/home.ts
  src/main/routes/importDefinition.ts
  src/main/routes/jurisdiction.ts
  src/main/routes/updateDefinition.ts
  src/main/routes/updateUser.ts
  src/main/routes/userProfiles.ts
  src/main/routes/userRoles.ts
  src/main/views/home.html
  src/main/views/importDefinition.html
  src/test/routes/confirmDeleteItem.spec.ts
  src/test/routes/home.spec.ts
  src/test/routes/importDefinition.spec.ts
Labels: checkpoint, ns:ccd-admin-web-pr-178
