Repository hmcts/ccd-admin-web, pull requests merged in 2019-01, with the labels that each got.

#122 Lock Terraform AzureRM provider to v1.19.0
  .travis.yml
  infrastructure/main.tf
Labels: ns:ccd-admin-web-pr-122

#123 Fix Sonar duplication issue
  config/default.yaml
  src/main/routes/definitions.ts
  src/main/routes/userProfiles.ts
  src/main/util/render.ts
  src/main/validators/validateJurisdiction.ts
  src/main/views/definitions.html
  src/main/views/user-profiles.html
Labels: ns:ccd-admin-web-pr-123

#126 Add test to cover validateJurisdiction validator
  src/test/validators/validateJurisdiction.spec.ts
Labels: ns:ccd-admin-web-pr-126

#127 Increase test coverage
  src/test/routes/definitions.spec.ts
  src/test/routes/userProfiles.spec.ts
Labels: ns:ccd-admin-web-pr-127

#128 RDM-2928: Draft Definitions list screen
  config/default.yaml
  src/main/routes/definitions.ts
  src/main/views/definitions.html
  src/test/routes/definitions.spec.ts
Labels: ns:ccd-admin-web-pr-128

#130 RDM-3686: Add missing environment variables
  infrastructure/main.tf
Labels: ns:ccd-admin-web-pr-130

#112 [PREVIEW] RDM-1956 Add to home page import audits
  config/default.yaml
  src/main/routes/home.ts
  src/main/views/home.html
  src/main/views/import-audits_inc.html
  src/test/routes/home.spec.ts
Labels: ns:ccd-admin-web-pr-112

#129 [PREVIEW] Shared App Insight
  config/default.yaml
  config/mocha.yaml
  config/test.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  src/main/app-insights/app-insights.spec.ts
  src/main/app-insights/app-insights.ts
  src/main/app.test.ts
  src/main/app.ts
  yarn.lock
Labels: ns:ccd-admin-web-pr-129

#137 [PREVIEW] RDM-3762 PREVIEW
  src/main/views/import-audits_inc.html
Labels: ns:ccd-admin-web-pr-137

#138 RDM-3015: Update Draft Definition
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  package.json
  src/main/domain/definition.ts
  src/main/routes/createDefinition.ts
  src/main/routes/updateDefinition.ts
  src/main/routes/updateUser.ts
  src/main/service/create-definition-service.ts
  src/main/views/definition/create-definition-form.html
  src/main/views/definitions.html
  src/test/routes/createDefinition.spec.ts
  src/test/routes/updateDefinition.spec.ts
  src/test/service/create-definition-service.spec.ts
  yarn.lock
Labels: checkpoint, ns:ccd-admin-web-pr-138

#109 Set minimum yarn version
  .travis.yml
  Dockerfile
  package.json
Labels: ns:ccd-admin-web-pr-109

#143 Bump snyk to v1.122.4
  package.json
  yarn.lock
Labels: ns:ccd-admin-web-pr-143
