Repository hmcts/ccd-admin-web, pull requests merged in 2019-04, with the labels that each got.

#203 switch idam_api_url and authentication_web_url
  infrastructure/demo.tfvars
Labels: ns:ccd-admin-web-pr-203

#204 change idam_api_url authentication_web_url SIDAM
  infrastructure/sprod.tfvars
Labels: ns:ccd-admin-web-pr-204

#208 updating SIDAM values
  infrastructure/saat.tfvars
Labels: ns:ccd-admin-web-pr-208

#209 Switch SIDAM
  infrastructure/demo.tfvars
Labels: ns:ccd-admin-web-pr-209

#213 RDM-3381: Display logged-in user and "Sign out" link
  charts/ccd-admin-web/values.aat.template.yaml
  charts/ccd-admin-web/values.template.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  src/main/app.test-admin-web-roles-authorized.ts
  src/main/app.ts
  src/main/public/stylesheets/app.scss
  src/main/routes/confirmDeleteItem.ts
  src/main/routes/createDefinition.ts
  src/main/routes/createUser.ts
  src/main/routes/home.ts
  src/main/routes/importDefinition.ts
  src/main/routes/jurisdiction.ts
  src/main/routes/logout.ts
  src/main/routes/updateDefinition.ts
  src/main/routes/updateUser.ts
  src/main/routes/userRoles.ts
  src/main/util/render.ts
  src/main/views/layout_template.html
  src/test/http-mocks/idam.ts
  src/test/routes/confirmDeleteItem.spec.ts
  src/test/routes/jurisdiction.spec.ts
  src/test/routes/logout.spec.ts
Labels: checkpoint, ns:ccd-admin-web-pr-213
