Repository hmcts/ccd-admin-web, pull requests merged in 2020-09, with the labels that each got.

#327 RDM-9262 - New page to trigger Elasticsearch indexing
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app.ts
  src/main/routes/indexElasticsearch.ts
  src/main/service/elastic-index-service.ts
  src/main/views/elasticsearch.html
  src/main/views/menu.html
  src/test/routes/indexElasticsearch.spec.ts
  src/test/service/elastic-index-service.spec.ts
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-327

#334 Rdm 9438 to develop
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-334

#330 Rdm 5300 - Security Vulnerabilities on Admin-web repo
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-330

#336 Release cut 19.2
  Jenkinsfile_CNP
  bin/run-yarn-audit.sh
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/values.preview.template.yaml
  charts/ccd-admin-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  src/main/app.ts
  src/main/routes/indexElasticsearch.ts
  src/main/service/elastic-index-service.ts
  src/main/views/elasticsearch.html
  src/main/views/menu.html
  src/test/routes/indexElasticsearch.spec.ts
  src/test/service/elastic-index-service.spec.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-336

#338 Rdm 9483 develop
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-338
