Repository hmcts/ccd-admin-web, pull requests merged in 2020-04, with the labels that each got.

#288 Force upgrade of assign-deep
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-admin-web-pr-288

#289 AKS prod migration
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-admin-web-pr-289

#291 ASE tf code cleanup
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/perftest.tfvars
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
Labels: ns:ccd, rel:ccd-admin-web-pr-291

#281 RDM-7843-Stale-PR
  .github/stale.yml
Labels: ns:ccd, rel:ccd-admin-web-pr-281

#290 RDM-8126
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/requirements.yaml
Labels: ns:ccd, rel:ccd-admin-web-pr-290

#293 OIDC Release
  .github/delete-merged-branch-config.yml
  src/main/user/user-resolver.ts
  src/test/http-mocks/idam.ts
Labels: ns:ccd, rel:ccd-admin-web-pr-293
