Repository hmcts/ccd-admin-web, pull requests merged in 2020-03, with the labels that each got.

#280 upgrade assign-deep
  yarn.lock
Labels: ns:ccd, rel:ccd-admin-web-pr-280

#273 RDM-7695 Update-IDAM-URLs
  infrastructure/ithc.tfvars
Labels: ns:ccd, rel:ccd-admin-web-pr-273

#284 Rdm 7695 update idam ur ls
  .travis.yml
  Dockerfile
  Jenkinsfile_CNP
  README.md
  _config.yml
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/requirements.yaml
  charts/ccd-admin-web/values.aat.template.yaml
  charts/ccd-admin-web/values.preview.template.yaml
  charts/ccd-admin-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  gulpfile.js
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  package.json
  src/main/app-insights/app-insights.ts
  src/main/oauth2/access-token-request.ts
  src/main/routes/importDefinition.ts
  src/main/routes/logout.ts
  src/main/service/service-token-generator.ts
  src/main/views/import-audits_inc.html
  src/main/views/importDefinition.html
  src/test/oauth2/access-token-request.spec.ts
  src/test/routes/importDefinition.spec.ts
  src/test/routes/logout.spec.ts
  yarn.lock
Labels: ns:ccd, rel:ccd-admin-web-pr-284

#279 Rdm 7636 - Migrate admin-web to oidc
  src/main/user/user-resolver.ts
  src/test/http-mocks/idam.ts
Labels: ns:ccd, rel:ccd-admin-web-pr-279

#285 RDM-7899-Slack
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-admin-web-pr-285

#283 RDM-7867-Update-base-chart
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/requirements.yaml
Labels: ns:ccd, rel:ccd-admin-web-pr-283

#286 Added missing Properties Volume dependency
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-admin-web-pr-286

#287 Loaded the properties-volume library
  server.js
Labels: ns:ccd, rel:ccd-admin-web-pr-287
