Repository hmcts/ccd-admin-web, pull requests merged in 2020-02, with the labels that each got.

#265 RDM-6888 Add 'Most recent uploads history' header. (#255)
  .nvmrc
  src/main/views/import-audits_inc.html
Labels: ns:ccd, rel:ccd-admin-web-pr-265

#264 Update Develop with Master (#255)
  src/main/views/import-audits_inc.html
Labels: ns:ccd, rel:ccd-admin-web-pr-264

#269 RDM-3593 - Update to node 12.x
  .travis.yml
  Dockerfile
  README.md
  gulpfile.js
  infrastructure/main.tf
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-admin-web-pr-269

#271 RDM-3593 - Update to node 12.x - MASTER
  .nvmrc
  .travis.yml
  Dockerfile
  README.md
  gulpfile.js
  infrastructure/main.tf
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-admin-web-pr-271

#270 RDM-7554 Remove the deprecated `enableDockerBuild()`
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-admin-web-pr-270

#275 AKS migration TF and package upgrade
  Dockerfile
  infrastructure/main.tf
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-admin-web-pr-275

#274 RDM-2508-Rm-nsp
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-admin-web-pr-274

#276 AKS Migration
  Jenkinsfile_CNP
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/values.aat.template.yaml
  charts/ccd-admin-web/values.preview.template.yaml
  charts/ccd-admin-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app-insights/app-insights.ts
  src/main/oauth2/access-token-request.ts
  src/main/routes/logout.ts
  src/main/service/service-token-generator.ts
  src/test/oauth2/access-token-request.spec.ts
  src/test/routes/logout.spec.ts
Labels: ns:ccd, rel:ccd-admin-web-pr-276

#277 fix master
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/requirements.yaml
  charts/ccd-admin-web/values.preview.template.yaml
  charts/ccd-admin-web/values.yaml
Labels: ns:ccd, rel:ccd-admin-web-pr-277

#278 remove ingress
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/values.yaml
Labels: ns:ccd, rel:ccd-admin-web-pr-278
