Repository hmcts/ccd-admin-web, pull requests merged in 2021-07, with the labels that each got.

#379 CCD-1325 CCD Broken Nightly Pipelines Admin web
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-379

#380 resolve all CVEs
  charts/ccd-admin-web/values.preview.template.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-380

#325 Develop
  charts/ccd-admin-web/values.preview.template.yaml
Labels: DO_NOT_MERGE, ns:ccd, prd:ccd, rel:ccd-admin-web-pr-325

#382 CCD-1584 Integrate Fortify Scan into Nightly Pipelines - C…
  Jenkinsfile_nightly
  package.json
  src/test/java/.gitignore
  src/test/java/build.gradle
  src/test/java/config/fortify-client.properties
  src/test/java/gradle/wrapper/gradle-wrapper.jar
  src/test/java/gradle/wrapper/gradle-wrapper.properties
  src/test/java/gradlew
  src/test/java/gradlew.bat
  src/test/java/settings.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-382

#383 fix for Fortify Issue 14640857 Dockerfile : 19
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-383
