Repository hmcts/ccd-admin-web, pull requests merged in 2021-03, with the labels that each got.

#354 RDM-10902 - Process case types one by one for ES indexing
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app.ts
  src/main/routes/indexElasticsearch.ts
  src/main/service/elastic-index-service.ts
  src/main/views/elasticsearch.html
  src/test/routes/indexElasticsearch.spec.ts
  src/test/service/elastic-index-service.spec.ts
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-354

#362 RDM-11415 Advisory-1605 and Advisory-1609
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-362

#363 RDM-11179: Fix the page loading delay due to app insights
  src/main/app-insights/app-insights.ts
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-363
