Repository hmcts/ccd-admin-web, pull requests merged in 2022-07, with the labels that each got.

#489 CCD-3457 : CVE-2021-43306: ccd-admin-web : Regular Expression Denial of Service in jquery-validation
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-489

#491 CCD-3464: Suppression and fix for moment.js CVE
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-491

#443 CCD-2496 multi arch image update
  Dockerfile
  Jenkinsfile_CNP
  acb.tpl.yaml
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-443

#486 CCD-965: Remove Temporary Sonar Exclusions ccd-admin-web
  package.json
  sonar-project.properties
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-486

#493 CCD-3559: CVE-2021-35065 suppress
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-493

#497 CCD-3463: ccd-admin-web CVE-2022-25758 suppress update
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-497

#496 CCD-3561 Upgrade Java and Node JS versions in chart for all the respe…
  charts/ccd-admin-web/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-496
