Repository hmcts/ccd-admin-web, pull requests merged in 2022-05, with the labels that each got.

#460 package update for CVE-2021-43138,CVE-2022-21803,CVE-2021-43138,CVE-2022-21803
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-460

#461 CVE-2020-7751 fix with pathval:1.1.1 version
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-461

#462 WLTS-11 get Welsh Translations
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  src/main/app.test-admin-web-roles-authorized.ts
  src/main/app.ts
  src/main/routes/welshDictionary.ts
  src/main/service/welsh-dictionary-service.ts
  src/main/views/menu.html
  src/main/views/welshDictionary.html
  src/test/service/welsh-dictionary-service.spec.ts
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-462

#464 suppression of CVE-2022-24434
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-464
