Repository hmcts/ccd-admin-web, pull requests merged in 2022-04, with the labels that each got.

#448 CVE-2022-24785-ccd-admin-web
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-448

#447 Fix a series of CVEs
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-447

#450 --Fix Nightly build
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-450

#452 --Fixed nightly build issue
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-452

#453 suppress temporarily
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-453

#455 Update yarn-audit-known-issues as descriptions have changed
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-455

#459 dependency check failure suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-459

#457 CVE-2022-24785 dependency fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-457
