Repository hmcts/ccd-admin-web, pull requests merged in 2022-12, with the labels that each got.

#527 Ignore the intermittently failing tests
  src/test/service/delete-definition-service.spec.ts
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-527

#517 CCD-3942 dependabot minimatch ReDoS vulnerability - resolution minima…
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-517

#536 CCD-4017 Upgrade base charts for Jenkins enhancements - bumped nodejs…
  charts/ccd-admin-web/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-536

#538 CCD-4107: Suppressions for CVE-2022-38900, CVE-2022-24999, CVE-2022-24999
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-538

#523 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-523

#541 CCD-4134 CVE-2022-46175 Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-541
