Repository hmcts/ccd-admin-web, pull requests merged in 2022-10, with the labels that each got.

#512 CCD-3784: Suppress CVE-2022-40764
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-512

#509 CCD-3773 Conditionally cleanup helm releases on PRs
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-509, keep-helm

#514 CCD-3742: Removed redundant package resolutions
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-514

#513 CCD-3784 CVE-2022-40764 snyk upgraded to ^1.996.0
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-513
