Repository hmcts/ccd-admin-web, pull requests merged in 2022-11, with the labels that each got.

#515 CCD-3802 Update to fortify-client version
  src/test/java/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-515

#516 WLTS-55 Support quotes in the middle of strings and null values
  src/main/service/manage-welsh-dictionary-service.ts
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-516

#520 CCD-CCD-4028 Manage Welsh Dictionary tests throwing errors - anonymou…
  src/test/routes/manageWelshDictionary.spec.ts
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-520

#521 CCD-4038 CVE-2022-38900 Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-521
