Repository hmcts/ccd-admin-web, pull requests merged in 2022-06, with the labels that each got.

#468 CCD-3334 Regular Pipeline Maintenance - suppression CVE-2021-43306
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-468

#472 CCD-3334 Regular Pipeline Maintenance - suppression CVE-2021-43306, C…
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-472

#469 update for CVE-2021-43306,CVE-2022-24434
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-469

#473 Revert "update for CVE-2021-43306,CVE-2022-24434"
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-473

#467 update for CVE-2022-24434
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-467

#475 CCD-3351: Dockerfile Fortify fix
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-475

#478 CCD-3393: Suppression for CVE-2022-33987
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-478

#481 CCD-3395: Suppression for CVE-2021-20066
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-481

#485 Fix for CCD-3393 , CCD-3395 , CCD-3418 and CCD-3419
  charts/ccd-admin-web/values.preview.template.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-485
