Repository hmcts/ccd-admin-web, pull requests merged in 2022-08, with the labels that each got.

#494 CCD-3559: Updated glob-parent to v6.0.1 and removed suppression
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-494

#502 CCD-3463: CVE-2022-25758 - removed node-sass dependency
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-502

#504 Add backstage configuration file
  catalog-info.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-504

#503 CCD-3632 fix for CVE-2022-33987
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-503
