Repository hmcts/ccd-admin-web, pull requests merged in 2022-02, with the labels that each got.

#422 CCD-2535: Temporarily ignore Fortify scan results
  src/test/java/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-422

#427 CVE-2020-15366 Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-427

#390 RDM-12714 Enable Global Search Index Creation/Recreation from AdminWeb
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  sonar-project.properties
  src/main/app.ts
  src/main/routes/indexGlobalSearch.ts
  src/main/service/global-search-index-service.ts
  src/main/views/globalsearch.html
  src/main/views/menu.html
  src/test/routes/indexGlobalSearch.spec.ts
  src/test/service/global-search-index-service.spec.ts
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-390

#430 Fix CVE-2021-23555 and remove suppression
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-430

#431 CCD-2658: CVE-2022-0536
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-431

#434 helm chart update
  charts/ccd-admin-web/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-434
