Repository hmcts/ccd-admin-web, pull requests merged in 2022-01, with the labels that each got.

#412 CCD-2389: Temporarily suppress CVE-2021-23490
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-412

#413 CCD-2389: Temporarily suppress CVE-2021-23490
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-413

#407 CCD-2293: Update hmcts/properties-volume dependency version
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-407

#414 CCD-2389: Address CVE-2021-23490
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-414

#418 CCD-2471: Temporarily suppress CVE-2022-0235
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-418

#411 CCD-2378: Re-enable Fortify scan
  Jenkinsfile_nightly
  src/test/java/build.gradle
  src/test/java/config/fortify-client.properties
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-411

#419 CVE-2022-0235
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-419

#420 CVE-2020-28503
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-420

#421 CVE-2020-28503
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-421
