Repository hmcts/ccd-admin-web, pull requests merged in 2023-01, with the labels that each got.

#543 CCD-4134 CVE-2022-46175 Redo Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-543

#545 CCD-4134 CVE-2022-46175 Redo Suppression 2nd Time
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-545

#542 CCD-4134 CVE-2022-46175 json5 resolution v2.2.2 added, yarn install r…
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-542

#535 CCD-4072: Intermittent Unit Test Failures ccd-admin-web
  package.json
  src/test/service/delete-definition-service.spec.ts
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-535

#547 Revert "CCD-4072: Intermittent Unit Test Failures ccd-admin-web"
  package.json
  src/test/service/delete-definition-service.spec.ts
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-547

#534 CCD-4088: updated express to 4.17.3 and removed suppression
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-534

#537 CCD-4097: Auto-suppress CVEs - Node JS apps
  .github/workflows/auto-suppress-CVEs.yml
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-537

#551 CCD-4173: Auto-suppress CVEs do not allow empty commit
  .github/workflows/auto-suppress-CVEs.yml
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-551

#548 CCD-4107 Snyk Update for CVE-2022-22984
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-548

#550 CCD-4156 Fix admin-web CVE-2022-38900, CVE-2022-22984
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-550

#539 CCD-3796 Update Node.js version to 16
  .nvmrc
  .travis.yml
  Dockerfile
  Jenkinsfile_CNP
  README.md
  acb.tpl.yaml
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-539

#552 CCD-3796 Update Node.js to version 16 - updated Jenkins files for Nig…
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-552
