Repository hmcts/ccd-admin-web, pull requests merged in 2023-09, with the labels that each got.

#592 Upgrade to Java 17 and latest gradle
  src/test/java/build.gradle
  src/test/java/gradle/wrapper/gradle-wrapper.jar
  src/test/java/gradle/wrapper/gradle-wrapper.properties
  src/test/java/gradlew
  src/test/java/gradlew.bat
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-592

#593 add suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-593

#582 CCD-4601 : Change manage translations endpoint
  charts/ccd-admin-web/values.preview.template.yaml
  package.json
  src/main/routes/welshDictionary.ts
  src/main/service/manage-welsh-dictionary-service.ts
  src/main/views/manageWelshDictionary.html
  src/test/service/manage-welsh-dictionary-service.spec.ts
  src/test/service/welsh-dictionary-service.spec.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, keep-helm, enable_keep_helm
