Repository hmcts/ccd-admin-web, pull requests merged in 2023-05, with the labels that each got.

#572 CCD-4582 : updated nunjucks to 3.2.4
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-572

#576 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-576

#575 CCD-4687 Update renovate.json
  .github/renovate.json
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-575
