Repository hmcts/ccd-admin-web, pull requests merged in 2024-04, with the labels that each got.

#603 Updated library version to resolve CVE
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-603

#608 updated nodejs version from 3.0.0 to 3.1.0 and chart version from 2.2…
  charts/ccd-admin-web/Chart.yaml
  charts/ccd-admin-web/values.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-608

#610 Add js-yaml
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-610
