Repository hmcts/ccd-admin-web, pull requests merged in 2024-09, with the labels that each got.

#615 suppressions updated
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-615

#617 CCD-5861 : CVE-2024-45296 : suppressions added
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-617

#619 cve_new1
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-619

#621 CVE_reDO
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-621
