Repository hmcts/ccd-admin-web, pull requests merged in 2025-06, with the labels that each got.

#642 CME-264: add indexing checkboxes
  package.json
  src/main/service/import-service.ts
  src/main/views/importDefinition.html
  src/test/service/import-service.spec.ts
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-642

#648 Revert "CME-264: add indexing checkboxes "
  package.json
  src/main/service/import-service.ts
  src/main/views/importDefinition.html
  src/test/service/import-service.spec.ts
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-648

#645 CME-554 Replaced jitpack with azure devops artifacts
  src/test/java/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-645

#647 CCD-6456 update chart to oci
  charts/ccd-admin-web/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-647
