Repository hmcts/ccd-admin-web, pull requests merged in 2025-03, with the labels that each got.

#636 CCD-6109:
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-636

#639 Test update corepack
  .dockerignore
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-639

#637 CCD-6112:
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-637

#640 CCD-6193 update chart version
  charts/ccd-admin-web/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-admin-web-pr-640
